# Generated by Django 5.0.2 on 2024-03-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0006_alter_progress_paid_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafeelStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafeel_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
