# Generated by Django 5.0.2 on 2024-03-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0007_kafeelstatusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafeel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Dropped Out', 'Dropped Out'), ('Course Complete', 'Course Complete')], default='Active', max_length=20),
        ),
    ]
