# Generated by Django 5.0.2 on 2024-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0008_kafeel_status_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
